// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mnema.Database;

#nullable disable

namespace Mnema.Database.SqliteMigrations
{
    [DbContext(typeof(SqliteMnemaDataContext))]
    partial class SqliteMnemaDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Authentication.AuthKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Roles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.HasKey("Id");

                    b.ToTable("AuthKeys");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("FollowedEvents")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Content.ContentRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGroupedRelease")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "ReleaseId")
                        .IsUnique();

                    b.ToTable("ContentReleases");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Content.DownloadClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFailed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("DownloadClients");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Content.ExternalDownload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Files")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<bool>("IsErrored")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.ToTable("ExternalDownloads");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Content.MonitoredChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Chapter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<float>("SortOrder")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("MonitoredChapters");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Content.MonitoredSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentFormat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardcoverId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDataRefreshUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MangaBakaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleOverride")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ValidTitles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MonitoredSeries");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Content.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Mnema.Models.Entities.ManualMigrationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RanAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ManualMigrationHistory");
                });

            modelBuilder.Entity("Mnema.Models.Entities.MetadataProviderSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ChapterCoverUrl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChapterPeople")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChapterReleaseDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChapterSummary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChapterTags")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChapterTitle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Chapters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetadataProvider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataProviderSpecific")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeriesAgeRating")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeriesCoverUrl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeriesLinks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeriesLocalizedName")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeriesPeople")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeriesPublicationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeriesSummary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeriesTags")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeriesTitle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeriesYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetadataProvider")
                        .IsUnique();

                    b.ToTable("MetadataProviderSettings");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<int>("Colour")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomRootDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultOptions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Preferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("BlackListedTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("ChapterFileFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ConvertToGenreList")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("CoverFallbackMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageFormat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OneShotFileFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PinSubscriptionTitles")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("WhiteListedTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "AgeRatingMappings", "Mnema.Models.Entities.Preferences.AgeRatingMappings#AgeRatingMappingDto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("AgeRating");

                            b1.Property<string>("Tag")
                                .IsRequired();

                            b1
                                .ToJson("AgeRatingMappings")
                                .HasColumnType("TEXT");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "LinkFilters", "Mnema.Models.Entities.Preferences.LinkFilters#LinkFilter", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Mode");

                            b1.Property<int>("Type");

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1
                                .ToJson("LinkFilters")
                                .HasColumnType("TEXT");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "MetadataFieldMappings", "Mnema.Models.Entities.Preferences.MetadataFieldMappings#MetadataFieldMappingDto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("DestinationType");

                            b1.Property<string>("DestinationValue")
                                .IsRequired();

                            b1.Property<bool>("ExcludeFromSource");

                            b1.Property<int>("Id");

                            b1.Property<int>("SourceType");

                            b1.Property<string>("SourceValue")
                                .IsRequired();

                            b1
                                .ToJson("MetadataFieldMappings")
                                .HasColumnType("TEXT");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "TagMappings", "Mnema.Models.Entities.Preferences.TagMappings#TagMappingDto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DestinationTag")
                                .IsRequired();

                            b1.Property<string>("OriginTag")
                                .IsRequired();

                            b1
                                .ToJson("TagMappings")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("Mnema.Models.Entities.ProviderSettings", b =>
                {
                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.HasKey("Provider");

                    b.ToTable("ProviderSettings");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Scanner.DirectoryImportResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Files")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<Guid>("ImportScanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MonitoredSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParsedHardcoverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParsedMangaBakaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParsedSeriesName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportScanId");

                    b.HasIndex("MonitoredSeriesId");

                    b.ToTable("DirectoryImportResults");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Scanner.ImportError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImportScanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportScanId");

                    b.ToTable("ImportErrors");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Scanner.ImportScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImportScans");
                });

            modelBuilder.Entity("Mnema.Models.Entities.ServerSetting", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Content.MonitoredChapter", b =>
                {
                    b.HasOne("Mnema.Models.Entities.Content.MonitoredSeries", "Series")
                        .WithMany("Chapters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Scanner.DirectoryImportResult", b =>
                {
                    b.HasOne("Mnema.Models.Entities.Scanner.ImportScan", "ImportScan")
                        .WithMany("DirectoryImportResults")
                        .HasForeignKey("ImportScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mnema.Models.Entities.Content.MonitoredSeries", "MonitoredSeries")
                        .WithMany()
                        .HasForeignKey("MonitoredSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImportScan");

                    b.Navigation("MonitoredSeries");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Scanner.ImportError", b =>
                {
                    b.HasOne("Mnema.Models.Entities.Scanner.ImportScan", "ImportScan")
                        .WithMany("ImportErrors")
                        .HasForeignKey("ImportScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportScan");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Content.MonitoredSeries", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Scanner.ImportScan", b =>
                {
                    b.Navigation("DirectoryImportResults");

                    b.Navigation("ImportErrors");
                });
#pragma warning restore 612, 618
        }
    }
}
