using System;
using System.IO;
using System.Threading.Tasks;
using System.Xml.Serialization;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Mnema.API.Content;
using Mnema.Common.Extensions;
using Mnema.Common.Helpers;
using Mnema.Models.External;
using Mnema.Models.Publication;

namespace Mnema.Providers.Managers.Publication;

internal partial class Publication
{
    private const string ComicInfoNote =
        "This comicinfo.xml was auto generated by Mnema, with information from {0}. Source code can be found here: https://github.com/Fesaa/Mnema/";
    private static readonly XmlSerializer XmlSerializer = new(typeof(ComicInfo));

    private readonly IMetadataService _metadataService = scope.ServiceProvider.GetRequiredService<IMetadataService>();

    private bool _hasNotifiedSeriesFullyDownloaded;

    private async Task WriteMetadataForChapter(Chapter chapter)
    {
        var coverUrl = string.IsNullOrEmpty(chapter.CoverUrl)
            ? Series!.NonProxiedCoverUrl ?? Series!.CoverUrl : chapter.CoverUrl;

        if (Request.GetKey(RequestConstants.IncludeCover))
            if (!string.IsNullOrEmpty(coverUrl))
            {
                try
                {
                    var filePath = Path.Join((string?)ChapterPath(chapter),
                        $"!0000 cover{coverUrl.GetUrlExtension()}");
                    var client = _httpClientFactory.CreateClient(provider.ToString());

                    await using var stream = await client.GetStreamAsync(coverUrl);
                    await using var file = _fileSystem.File.Create(filePath);
                    await stream.CopyToAsync(file);
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "[{Title}/{Id}] An exception occured writing the cover from {Url}", Title, Id, coverUrl);
                }
            }

        var ci = _metadataService.CreateComicInfo(Preferences, Request, Title, Series, chapter, string.Format(ComicInfoNote, provider.ToString()));
        if (ci != null)
        {
            if (IsMonitored && ci.Finished && !_hasNotifiedSeriesFullyDownloaded)
            {
                _hasNotifiedSeriesFullyDownloaded = true;
                _connectionService.CommunicateSeriesExhausted(DownloadInfo);
            }

            var ciPath = Path.Join((string?)ChapterPath(chapter), "ComicInfo.xml");
            XmlHelper.SerializeToFile(XmlSerializer, ci, ciPath);
        }
    }
}
