// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mnema.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mnema.Database.Migrations
{
    [DbContext(typeof(MnemaDataContext))]
    [Migration("20251216215546_AddSubscriptionTitle")]
    partial class AddSubscriptionTitle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mnema.Models.Entities.Content.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseDir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastDownloadDir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastRun")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LastRunSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"StartImmediately\":false,\"Extra\":{}}");

                    b.Property<DateTime>("NextRun")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NoDownloadsRuns")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Mnema.Models.Entities.ServerSetting", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("Mnema.Models.Entities.UI.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomRootDir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Dirs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Providers")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("SortValue")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Modifiers", "Mnema.Models.Entities.UI.Page.Modifiers#ModifierDto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Key")
                                .IsRequired();

                            b1.Property<int>("Sort");

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.Property<int>("Type");

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Values", "Mnema.Models.Entities.UI.Page.Modifiers#ModifierDto.Values#ModifierValueDto", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<bool>("Default");

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();
                                });

                            b1.ToJson("Modifiers");
                        });

                    b.HasKey("Id");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Mnema.Models.Entities.User.MnemaUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mnema.Models.Entities.User.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<int>("Colour")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Mnema.Models.Entities.User.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("BlackListedTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new string[0]);

                    b.PrimitiveCollection<string[]>("ConvertToGenreList")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new string[0]);

                    b.Property<int>("CoverFallbackMethod")
                        .HasColumnType("integer");

                    b.Property<int>("ImageFormat")
                        .HasColumnType("integer");

                    b.Property<bool>("PinSubscriptionTitles")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("WhiteListedTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new string[0]);

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "AgeRatingMappings", "Mnema.Models.Entities.User.UserPreferences.AgeRatingMappings#AgeRatingMappingDto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("AgeRating");

                            b1.Property<string>("Tag")
                                .IsRequired();

                            b1.ToJson("AgeRatingMappings");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "TagMappings", "Mnema.Models.Entities.User.UserPreferences.TagMappings#TagMappingDto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DestinationTag")
                                .IsRequired();

                            b1.Property<string>("OriginTag")
                                .IsRequired();

                            b1.ToJson("TagMappings");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("MnemaUserPage", b =>
                {
                    b.Property<Guid>("PagesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("PagesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("MnemaUserPage");
                });

            modelBuilder.Entity("Mnema.Models.Entities.Content.Subscription", b =>
                {
                    b.HasOne("Mnema.Models.Entities.User.MnemaUser", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mnema.Models.Entities.User.Notification", b =>
                {
                    b.HasOne("Mnema.Models.Entities.User.MnemaUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mnema.Models.Entities.User.UserPreferences", b =>
                {
                    b.HasOne("Mnema.Models.Entities.User.MnemaUser", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Mnema.Models.Entities.User.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MnemaUserPage", b =>
                {
                    b.HasOne("Mnema.Models.Entities.UI.Page", null)
                        .WithMany()
                        .HasForeignKey("PagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mnema.Models.Entities.User.MnemaUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mnema.Models.Entities.User.MnemaUser", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
