using Mnema.API.Content;
using Mnema.Common.Extensions;
using Mnema.Common.Helpers;
using Mnema.Models.DTOs.User;
using Mnema.Models.External;
using Mnema.Models.Publication;

namespace Mnema.Providers;

internal partial class Publication
{

    private const string ComicInfoNote = "This comicinfo.xml was auto generated by Mnema, with information from {0}. Source code can be found here: https://github.com/Fesaa/Mnema/";

    private bool _hasNotifiedSubscriptionExhausted = false;
    
    private async Task WriteMetadataForChapter(Chapter chapter)
    {
        var coverUrl = string.IsNullOrEmpty(chapter.CoverUrl) ? _series!.CoverUrl : chapter.CoverUrl;

        if (Request.GetBool(RequestConstants.IncludeCover, true))
        {
            if (!string.IsNullOrEmpty(coverUrl))
            {
                var filePath = Path.Join(ChapterPath(chapter), $"!0000 cover{_fileSystem.Path.GetExtension(coverUrl)}");
                var client = _httpClientFactory.CreateClient(provider.ToString());

                await using var stream = await client.GetStreamAsync(coverUrl);
                await using var file = _fileSystem.File.Create(filePath);
                await stream.CopyToAsync(file);
            }
        }

        var ci = BuildComicInfoForChapter(chapter);
        if (ci != null)
        {
            var ciPath = Path.Join(ChapterPath(chapter), "ComicInfo.xml");
            XmlHelper.SerializeToFile(ci, ciPath);
        }
    }

    private ComicInfo? BuildComicInfoForChapter(Chapter chapter)
    {
        if (_series == null) return null;
        
        var ci = new ComicInfo
        {
            Notes = string.Format(ComicInfoNote, provider.ToString()),
            Series = Title,
            AlternateSeries = _series.AltTitle ?? string.Empty,
            Summary = chapter.Summary.OrNonEmpty(_series.Summary),
            Title = chapter.Title,
        };

        if (chapter.VolumeNumber() != null)
        {
            ci.Volume = chapter.VolumeMarker;
        }

        if (chapter.IsOneShot)
        {
            ci.Format = "Special";
        }
        else
        {
            ci.Number = chapter.ChapterMarker;
        }
        
        foreach (var role in Enum.GetValues<PersonRole>())
        {
            var value = string.Join(',', _series.People
                .Where(p => p.Roles.Contains(role))
                .Select(p => p.Name));
            ci.SetForRole(value, role);
        }

        ci.Web = string.Join(',', _series.Links.Concat([_series.RefUrl]).Distinct());

        var allTags = _series.Tags.Concat(chapter.Tags).ToList();
        (ci.Genre, ci.Tags) = GetGenreAndTags(allTags);

        var ar = GetAgeRating(allTags);
        if (ar != null)
        {
            ci.AgeRating = ar.Value;
        }

        var (count, finished) = GetCount();
        
        if (count == null)
        {
            return ci;
        }

        ci.Count = count.Value;

        if (_hasNotifiedSubscriptionExhausted || Request.SubscriptionId == null || !finished)
        {
            return ci;
        }

        _hasNotifiedSubscriptionExhausted = true;
        
        // TODO: Add notification that subscription has downloaded everything

        return ci;
    }

    private static List<Tag> MapTags(IList<Tag> tags, IList<TagMappingDto> mappings)
    {
        return tags.Select(tag =>
        {
            var tagValue = tag.Value.ToNormalized();
            var tagId = tag.Id.ToNormalized();

            return new Tag
            {
                Id = mappings.FirstOrDefault(m => m.OriginTag == tagId)?.DestinationTag ?? tag.Id,
                Value = mappings.FirstOrDefault(m => m.OriginTag == tagValue)?.DestinationTag ?? tag.Value,
                IsMarkedAsGenre = tag.IsMarkedAsGenre,
            };
        }).ToList();
    }

    private (string, string) GetGenreAndTags(IList<Tag> allTags)
    {
        var mapToGenre = _preferences.ConvertToGenreList.Select(g => g.ToNormalized()).ToList();
        var blackListed = _preferences.BlackListedTags.Select(g => g.ToNormalized()).ToList();
        var whiteListed = _preferences.WhiteListedTags.Select(g => g.ToNormalized()).ToList();
        var mappings = _preferences.TagMappings.Select(m => m with
        {
            OriginTag = m.OriginTag.ToNormalized(),
        }).ToList();

        allTags = MapTags(allTags, mappings);

        var filteredGenres = allTags.Where(TagAllowedAsGenre).Select(t => t.Value).Distinct();
        var filteredTags = allTags.Where(TagAllowedAsTag).Select(t => t.Value).Distinct();

        return (string.Join(',', filteredGenres), string.Join(',', filteredTags));

        bool TagAllowedAsGenre(Tag tag)
        {
            var tagValue = tag.Value.ToNormalized();
            var tagId = tag.Id.ToNormalized();

            var isBlackListed = blackListed.Contains(tagValue) || blackListed.Contains(tagId);
            if (isBlackListed) return false;

            return tag.IsMarkedAsGenre || mapToGenre.Contains(tagValue) || mapToGenre.Contains(tagId);
        }

        bool TagAllowedAsTag(Tag tag)
        {
            var tagValue = tag.Value.ToNormalized();
            var tagId = tag.Id.ToNormalized();

            var isBlackListed = blackListed.Contains(tagValue) || blackListed.Contains(tagId);
            if (isBlackListed) return false;

            if (TagAllowedAsGenre(tag)) return false;

            if (Request.GetBool(RequestConstants.IncludeNotMatchedTagsKey)) return true;

            return whiteListed.Contains(tagValue) || whiteListed.Contains(tagId);
        }
    }

    private AgeRating? GetAgeRating(IList<Tag> allTags)
    {
        var mappings = _preferences.TagMappings.Select(m => m with
        {
            OriginTag = m.OriginTag.ToNormalized(),
        }).ToList();

        var ageRatingMappings = _preferences.AgeRatingMappings.Select(m => m with
        {
            Tag = m.Tag.ToNormalized(),
        }).ToList();
        
        allTags = MapTags(allTags, mappings);

        var ageRatings = allTags
            .Select(GetAgeRatingForTag)
            .Concat([_series!.AgeRating])
            .WhereNotNull()
            .ToList();

        return ageRatings.Count == 0 ? null : ageRatings.Max();

        AgeRating? GetAgeRatingForTag(Tag tag)
        {
            var tagValue = tag.Value.ToNormalized();
            var tagId = tag.Id.ToNormalized();

            var tagAgeRating = AgeRating.Unknown;
            
            foreach (var mapping in ageRatingMappings)
            {
                if (mapping.Tag != tagValue && mapping.Tag != tagId)
                    continue;
                
                tagAgeRating = tagAgeRating > mapping.AgeRating ? tagAgeRating : mapping.AgeRating;
            }

            return tagAgeRating > AgeRating.Unknown ? tagAgeRating : null;
        }
    }

    private (int?, bool) GetCount()
    {
        if (_series == null) return (null, false);

        if (_series.Status != PublicationStatus.Completed)
        {
            return (null, false);
        }

        if (_series.TranslationStatus != null && _series.TranslationStatus != PublicationStatus.Completed)
        {
            return (null, false);
        }

        var chapterNumbers = _series.Chapters.Select(c => c.ChapterNumber()).WhereNotNull().ToList();
        var volumeNumbers = _series.Chapters.Select(c => c.VolumeNumber()).WhereNotNull().ToList();

        var highestChapter = chapterNumbers.Count == 0 ? null : chapterNumbers.Max();
        var highestVolume = volumeNumbers.Count == 0 ? null : volumeNumbers.Max();

        if (_series.HighestVolumeNumber != null)
        {
            return ((int?)_series.HighestVolumeNumber, _series.HighestVolumeNumber.SafeEquals(highestVolume));
        }
        
        if (_series.HighestChapterNumber != null)
        {
            return ((int?)_series.HighestChapterNumber, _series.HighestChapterNumber.SafeEquals(highestChapter));
        }

        if (highestVolume != null)
        {
            return ((int?)highestVolume, true);
        }
        
        if (highestChapter != null)
        {
            return ((int?)highestChapter, true);
        }

        return (null, false);

    }
    
    
}