name: Release Workflow

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  issues: write
  pull-requests: read
  packages: write

jobs:
  run-release-tool:
    uses: Kareadita/GitHubActions/.github/workflows/release-tools.base.yml@feature/no-pr-deps
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    with:
      config-path: release.yaml
      uses-docker: true
